/**
 * IronFunctions
 * null
 *
 * OpenAPI spec version: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NewTask'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NewTask'));
  } else {
    // Browser globals (root is window)
    if (!root.IronFunctions) {
      root.IronFunctions = {};
    }
    root.IronFunctions.NewTasksWrapper = factory(root.IronFunctions.ApiClient, root.IronFunctions.NewTask);
  }
}(this, function(ApiClient, NewTask) {
  'use strict';




  /**
   * The NewTasksWrapper model module.
   * @module model/NewTasksWrapper
   * @version 0.0.5
   */

  /**
   * Constructs a new <code>NewTasksWrapper</code>.
   * @alias module:model/NewTasksWrapper
   * @class
   * @param tasks {Array.<module:model/NewTask>} 
   */
  var exports = function(tasks) {
    var _this = this;

    _this['tasks'] = tasks;
  };

  /**
   * Constructs a <code>NewTasksWrapper</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewTasksWrapper} obj Optional instance to populate.
   * @return {module:model/NewTasksWrapper} The populated <code>NewTasksWrapper</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tasks')) {
        obj['tasks'] = ApiClient.convertToType(data['tasks'], [NewTask]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/NewTask>} tasks
   */
  exports.prototype['tasks'] = undefined;



  return exports;
}));


