/**
 * IronFunctions
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.1.29
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IronFunctions);
  }
}(this, function(expect, IronFunctions) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IronFunctions.AppsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AppsApi', function() {
    describe('appsAppDelete', function() {
      it('should call appsAppDelete successfully', function(done) {
        //uncomment below and update the code to test appsAppDelete
        //instance.appsAppDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appsAppGet', function() {
      it('should call appsAppGet successfully', function(done) {
        //uncomment below and update the code to test appsAppGet
        //instance.appsAppGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appsAppPatch', function() {
      it('should call appsAppPatch successfully', function(done) {
        //uncomment below and update the code to test appsAppPatch
        //instance.appsAppPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appsGet', function() {
      it('should call appsGet successfully', function(done) {
        //uncomment below and update the code to test appsGet
        //instance.appsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('appsPost', function() {
      it('should call appsPost successfully', function(done) {
        //uncomment below and update the code to test appsPost
        //instance.appsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
